### ISSUE TITLE
Incorrect documentation in docs folder

### ISSUE THREAD

**Issue by Grandolf49** [openMF/fineract-client#13]
The documentation generated by Swagger Codegen is incorrect.
Eg: [AccountNumberFormatApi.md](https://github.com/openMF/fineract-client/blob/master/docs/AccountNumberFormatApi.md)
In the documentation, the Base URL contains an additional **http://** string. This was because the API Spec File was incorrect. It has been fixed now.
 
This might be a tedious task to solve. [This](https://gist.github.com/Grandolf49/62b084ebeec49ae56f729466d0c5ceb0) file was used to generate the client library. 

**Possible Resolution**
1. Use the Spec File URL and generate library again.
2. Verify if the documentation generated is correct or not.
3. If correct, copy all the doc files and paste them in this project
4. If not, use Mustache Templates to generate correct documentation in Swagger Codegen

**Comment by danishjamal104** [comment]
this issue doesn't  exist for `v1.5.0` check out here [AccountNumberFormatApi.md](https://github.com/openMF/fineract-client/blob/development-1.5.0/docs/AccountNumberFormatApi.md)

**Comment by danishjamal104** [comment]
For this we don't need to make the changes to the mustache file since it uses `basePath` as variable we can modify that instead to make sure that url is correct. Take a look here [markdown-documentation](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/markdown-documentation).

For modifying the base url, now we need to modify the server url(line-25) inside [fineract-provider/config/swagger/fineract-input.yaml.template](https://github.com/apache/fineract/blob/develop/fineract-provider/config/swagger/fineract-input.yaml.template)
